version: "3"
services:
  webapp:
    image: onlab-webapp_webapp
#    build:
#      context: .
#      dockerfile: Dockerfile
    deploy:
      replicas: 2
    ports:
      - "8080:8080"
  prometheus:
    depends_on:
      - webapp
    image: onlab-webapp_prometheus
#    build: ./prometheus
    ports:
      - "9090:9090"
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
  prediction:
    depends_on:
      - prometheus
#    build:
#      context: ./clients/predicting
#      dockerfile: Dockerfile
    image: onlab-webapp_prediction
    environment:
      - ONLAB_WEBAPP_URL=http://webapp:8080/time
      - TIME_BEFORE_PRED_START=100
      - PREDICTION_INTERVAL=30
    command: pipenv run python -u resource_predict.py
    ports:
      - "8000:8000"
volumes:
  grafana-data:
    external: true


